---

- name: fail when package is not installed
  fail:
    msg: "Package {{ service_package_name }}-{{ service_package_version }} is currently not installed"
  when: (package_condition is not defined) or (package_condition == false)

- name: set variable
  set_fact:
    current_launch_daemon_script_path: "{{ launch_daemons_base_path }}/{{ launch_daemon_prefix }}.{{ service_package_name }}-{{ service_package_version }}.plist"

- name: "check if launch daemon script exists"
  stat:
    path: "{{ current_launch_daemon_script_path }}"
  register: current_launch_daemon_script_path_obj

- name: fail when package has no launch daemon script
  fail:
    msg: "Package {{ service_package_name }}-{{ service_package_version }} has no launch daemon script"
  when: current_launch_daemon_script_path_obj.stat.exists == false

- name: "@vsh stopping service {{ service_package_name }}-{{ service_package_version }}"
  command: "launchctl unload -w {{ launch_daemons_base_path }}/{{ launch_daemon_prefix }}.{{ service_package_name }}-{{ service_package_version }}.plist"
  become: true
