---

- set_fact:
    package:
      name: "php"
      version: "5.6"
      config:
        role_path: "{{ role_path }}"
        directories:
          - "{{ package_etc_path }}/conf-available"
        templates:
          - source: "templates/php5.6.j2"
            target: "/usr/local/bin/php5.6"
            mode: "0755"
          - source: "templates/fpm.conf.j2"
            target: "{{ package_etc_path }}/fpm.conf"
            mode: "0755"
          - source: "templates/php.ini.j2"
            target: "{{ package_etc_path }}/php.ini"
            mode: "0755"
          - source: "templates/conf/xdebug.ini.j2"
            target: "{{ package_etc_path }}/conf-available/xdebug.ini"
            mode: "0755"
          - source: "templates/conf/opcache.ini.j2"
            target: "{{ package_etc_path }}/conf-available/opcache.ini"
            mode: "0755"