---

- name: fail when dnsmasq_domain is not set
  fail:
    msg: "'dnsmasq_domain' var is not set"
  when: dnsmasq_domain is not defined


- name: ensure resolver directory '/etc/resolver/' exists
  file:
    path: "/etc/resolver"
    state: directory
    mode: 0755
  become: true

- name: "set resolver configuration for domain '{{ dnsmasq_domain }}'"
  copy:
    content: "nameserver 127.0.0.1"
    dest: "/etc/resolver/{{ dnsmasq_domain }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: "set dnsmasq configuration for domain '{{ dnsmasq_domain }}'"
  copy:
    content: "address=/{{ dnsmasq_domain }}/127.0.0.1"
    dest: "{{ package_etc_path }}/conf.d/{{ dnsmasq_domain }}.conf"

- name: start service via service-manager
  include_role:
    name: service-manager
  vars:
    service_action: restart
    service_package_name: "{{ current_package_name }}"
    service_package_version: "{{ current_package_version }}"
