---
distil_base_url: "https://distil.valet.sh"

working_dir: "{{ lookup('env','PWD') }}"
base_path: "/usr/local/valet-sh"

valet_sh_base_path: "/usr/local/valet-sh"
valet_sh_etc_path: "{{ valet_sh_base_path }}/etc"

packages_state_file: "{{ base_path }}/package_state"
defaults_state_file: "{{ base_path }}/defaults_state"
launch_daemons_base_path: "/Library/LaunchDaemons"
launch_daemon_prefix: "sh.valet"

package_channel: "testing"

current_user: "{{ lookup('env','USER') }}"
current_group: "staff"

package_user: "{{ current_user }}"
package_group: "{{ current_group }}"

# linux only
# package_group: "{{ lookup('env','USER') }}"


package_defaults:
  - "gnutar": "1.3"

essential_packages:
  - package_name: "gnutar"
    package_version: "1.3"

