---

dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: dellxps-test-xenial
    alias: ubuntu/bionic
provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
  lint:
    name: ansible-lint
    enabled: true
scenario:
  name: default
#verifier:
#  name: testinfra
#  lint:
#    name: flake8
