---

- name: ensure universe repository is enabled
  shell: "add-apt-repository -y universe"

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- apt_repository:
    repo: ppa:linrunner/tlp
    update_cache: yes

- name: install tlp packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - thermald
      - tlp
      - tlp-rdw
      - powertop

- name: Fix Sleep/Wake Bluetooth Bug
  lineinfile:
    path: /etc/default/tlp
    regexp: '^RESTORE_DEVICE_STATE_ON_STARTUP'
    line: 'RESTORE_DEVICE_STATE_ON_STARTUP=1'

- name: Fix Audio Feedback/White Noise from Headphones on Battery Bug
  lineinfile:
    path: /etc/default/tlp
    regexp: '^SOUND_POWER_SAVE_ON_BAT'
    line: 'SOUND_POWER_SAVE_ON_BAT=0'

- name: ensure tlp service is restarted
  systemd:
    state: restarted
    name: tlp

- name: "enable graphic drivers ppa"
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes

- name: "run ubuntu-drivers autoinstall"
  shell: "ubuntu-drivers autoinstall"

- name: install video codec packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ubuntu-restricted-extras
      - va-driver-all
      - vainfo
      - libva2
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi

- apt_repository:
    repo: ppa:eh5/pulseaudio-a2dp
    update_cache: yes

- name: install video codec packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libavcodec58
      - libldac
      - pulseaudio-modules-bt

- name: install intel microcode updates
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - intel-microcode

- name: Download ath10k board.bin
  get_url:
    url: https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board.bin?raw=true
    dest: /lib/firmware/ath10k/QCA6174/hw3.0/board.bin
    force: yes

- name: Download ath10k board-2.bin
  get_url:
    url: https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board-2.bin?raw=true
    dest: /lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin
    force: yes

- name: Download ath10k firmware-4.bin
  get_url:
    url: https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/firmware-4.bin_WLAN.RM.2.0-00180-QCARMSWPZ-1?raw=true
    dest: /lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
    force: yes

- name: Enable power saving tweaks for Intel chip
  lineinfile:
    path: /etc/modprobe.d/i915.conf
    line: 'options i915 enable_fbc=1 enable_guc=3 disable_power_well=0 fastboot=1'
    create: true

- name: enable fan speed with lm-sensors
  lineinfile:
    path: /etc/modprobe.d/dell-smm-hwmon.conf
    line: 'options dell-smm-hwmon restricted=0 force=1'
    create: true

- name: enable dell specific module
  lineinfile:
    path: /etc/modules
    line: 'dell-smm-hwmon'

- name: "run update-initramfs -u"
  shell: "update-initramfs -u"

- name: "switch to intel gpu"
  shell: "prime-select intel"

- name: update grub config
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_OPTIONS="'
    line: 'GRUB_OPTIONS="quiet splash acpi_rev_override=1 acpi_osi=Linux nouveau.modeset=0 pcie_aspm=force drm.vblankoffdelay=1 scsi_mod.use_blk_mq=1 nouveau.runpm=0 mem_sleep_default=deep"'

- name: "run update-grub"
  shell: "update-grub"

- name: disable gnome tracker apps
  systemd:
    masked: yes
    name: "{{ item }}"
  with_items:
    - tracker-extract.desktop
    - tracker-miner-apps.desktop
    - tracker-miner-fs.desktop
    - tracker-store.desktop

- name: disable fingerprint reader
  lineinfile:
    path: /etc/udev/rules.d/fingerprint.rules
    line: 'SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"27c6\", ATTRS{idProduct}==\"5395\", ATTR{authorized}=\"0\"'
    create: true
