---

- name: ca | ensure base directories existing
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: staff
    mode: '0755'
  with_items:
    - "{{ certificate_ca_path }}"
  become: true

- name: ca | generate private ca key
  shell: "openssl genrsa -out {{ certificate_ca_key_file }} {{ certificate_ca_key_size }}"
  args:
    creates: "{{ certificate_ca_key_file }}"
  become: true

- name: ca | generate CA Certificate
  shell: "openssl req -subj '/CN=valet.sh development CA/O=valet.sh/C=DE' -x509 -new -nodes -key {{ certificate_ca_key_file }} -sha256 -days {{ certificate_ca_lifetime }} -out {{ certificate_ca_cert_file }}"
  args:
    creates: "{{ certificate_ca_cert_file }}"
  register: generate_ca_certificate_obj
  become: true

- name: ca | update ca certificates keystore
  shell: "security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {{ certificate_ca_cert_file }}"
  when: generate_ca_certificate_obj.changed|bool
  become: true
