---

certificate_base_path: "/usr/local/valet-sh/etc"

certificate_ca_path: "{{ certificate_base_path }}/ca"
certificate_ca_cert_file: "{{ certificate_ca_path }}/cacert.pem"
certificate_ca_key_file: "{{ certificate_ca_path }}/privkey.pem"
certificate_ca_key_size: 4096
certificate_ca_lifetime: 3650

certificate_client_key_size: 2048
certificate_client_cert_lifetime: 1825
certificate_client_key_filename: privkey.pem
certificate_client_csr_filename: csr.pem
certificate_client_cert_filename: cert.pem
certificate_client_fullchain_filename: fullchain.pem


certificate_domain_base_path: "{{ certificate_wildcard_cert_path }}/{{ certificate_client_domain }}"
certificate_domain_key_file: "{{ certificate_domain_base_path }}/{{ certificate_client_key_filename }}"
certificate_domain_csr_file: "{{ certificate_domain_base_path }}/{{ certificate_client_csr_filename }}"
certificate_domain_cert_file: "{{ certificate_domain_base_path }}/{{ certificate_client_cert_filename }}"
certificate_domain_fullchain_file: "{{ certificate_domain_base_path }}/{{ certificate_client_fullchain_filename }}"
