---
install_java_filename: 'jdk-8u181-macosx-x64.dmg'
install_java_mount: 'JDK 8 Update 181'
install_elasticsearch_download_baseurl: 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-'
install_elasticsearch_version: '6.5.4'
install_elasticsearch_config_version: '6'
install_elasticsearch_plugin_bin: 'elasticsearch-plugin'
install_elasticsearch_plugins:
  - "analysis-phonetic"
  - "analysis-icu"