---

- name: check path to startup script template
  stat:
    path: "{{ package.config.role_path }}/templates/{{ package_startup_script }}.j2"
  register: package_startup_script_obj

- name: "provision startup-script"
  template:
    src: "{{ package_startup_script_obj.stat.path }}"
    dest: "{{ launch_daemons_base_path }}/{{ package_startup_script }}"
    mode: "644"
  when: package_startup_script_obj.stat.exists
  become: true

- name: "provision templates"
  template:
    src: "{{ package.config.role_path }}/{{ package_template_item.source }}"
    dest: "{{ package_template_item.target }}"
    mode: "{{ package_template_item.mode | default('644') }}"
  with_items: "{{ package.config.templates }}"
  loop_control:
    loop_var: package_template_item
  when: package.config.templates is defined
  become: true

- name: "provision files"
  template:
    src: "{{ package.config.role_path }}/{{ package_file_item.source }}"
    dest: "{{ package_file_item.target }}"
    mode: "{{ package_file_item.mode | default('644') }}"
  with_items: "{{ package.config.files }}"
  loop_control:
    loop_var: package_file_item
  when: package.config.files is defined
  become: true

- name: "call install tasks for {{ current_package_name }}-{{ current_package_version }}"
  include_role:
    name: "package-{{ current_package_name }}-{{ current_package_version }}"
  vars:
    package_action: "{{ package.config.install.package_action }}"
  when: (package.config.install is defined) and (package.config.install.package_action is defined)

- name: "add links to /usr/local/bin"
  file:
    src: "{{ package_link_item.source }}"
    dest: "{{ package_link_item.target }}"
    state: link
    force: true
  with_items: "{{ package.config.links }}"
  loop_control:
    loop_var: package_link_item
  when: package.config.links is defined
  become: true
