---

- name: "fail when purge was not confirmed"
  fail:
    msg: "purge was not confirmed"
  when: (confirm_purge is not defined) or (confirm_purge != "yes")

- name: stop service via service-manager
  include_role:
    name: service-manager
  vars:
    service_action: stop
    service_package_name: "{{ current_package_name }}"
    service_package_version: "{{ current_package_version }}"
    service_mode: soft

- name: set package_base_path
  set_fact:
    package_base_path: "{{ base_path }}/{{ current_package_name }}/{{ current_package_version }}"
    package_startup_script: "{{ launch_daemon_prefix }}.{{ current_package_name }}-{{ current_package_version }}.plist"

- name: "delete launch daemon script for {{ current_package_name }}-{{ current_package_version }}"
  file:
    state: absent
    path: "{{ package_startup_script }}"

- name: "delete all package files {{ current_package_name }}-{{ current_package_version }}"
  file:
    state: absent
    path: "{{ package_base_path }}"

- name: update state-manager
  include_role:
    name: state-manager
  vars:
    state_action: delete_state
    state_package_name: "{{ current_package_name }}"
    state_package_version: "{{ current_package_version }}"
    state_mode: soft
