---

php56_fpm_socket_path: "/tmp/{{ current_package_name }}{{ current_package_version }}-fpm.sock"

php56_default_ini_settings:
  - conf: "date.timezone"
    value: "Europe/Berlin"

  - conf: "max_execution_time"
    value: "900"

  - conf: "error_log"
    value: "/tmp/{{ current_package_name }}{{ current_package_version }}_errors.log"

  - conf: "memory_limit"
    value: "4096M"

  - conf: "upload_max_filesize"
    value: "128M"

  - conf: "post_max_size"
    value: "128M"

  - conf: "max_input_vars"
    value: "10000"

php56_custom_ini_settings: []