#!/usr/bin/env ansible-playbook
---
#
# valet.sh
#
# @author: "Johann Zelger"
# @command: "distil:install"
# @description: "Install distil packages"
# @subcommands: ["all","redis"]

- name: "distil:install"
  hosts: local
  gather_facts: True

  roles:
    - gnutar
    - redis
    - php
