#!/usr/bin/env ansible-playbook
---
#
# valet.sh | elasticsearch
#
# @author: "Johann Zelger"
# @description: "Elasticsearch privisioning commands"

- name: "install elasticsearch v5"
  hosts: local
  gather_facts: True
  roles:
    - role: java
    - role: elasticsearch
  vars:
    install_java_filename: 'jdk-8u181-macosx-x64.dmg'
    install_java_mount: 'JDK 8 Update 181'
    install_elasticsearch_download_baseurl: 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-'
    install_elasticsearch_version: '5.6.12'
    install_elasticsearch_config_version: '5'
    install_elasticsearch_plugin_bin: 'elasticsearch-plugin'
    install_elasticsearch_plugins:
    - "analysis-phonetic"
    - "analysis-icu"