#
# valet.sh | links
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "links"
# @platform: macOS Ubuntu
# @sudo: true
# @description: "Show all currently linked sites"
# @usage: "valet.sh links"
# @help:
#
# list all existing linked projects
# valet.sh links
#
---
- name: "links"
  hosts: local
  gather_facts: True
  vars:
    valet_action: links
  roles:
    - valet-link