#
# valet.sh | unlink
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "unlink"
# @description: "Unlink current directory with given name"
# @usage: "valet.sh unlink <name>"
# @help:
#
# unlink a project. Deletes only the nginx configuration
# valet.sh unlink <linkname>
#
---
- name: "unlink"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  vars:
    valet_action: unlink
    link_name: "{{ cli.args[0] }}"
  roles:
    - valet-link